// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHatwUC-iMkIPE8BjdRPNxqKDuzObAns',
    appId: '1:728113313967:web:a4e325f98e6c0f24033c5a',
    messagingSenderId: '728113313967',
    projectId: 'itgustmobileplatform',
    authDomain: 'itgustmobileplatform.firebaseapp.com',
    storageBucket: 'itgustmobileplatform.appspot.com',
    measurementId: 'G-H3VKZM4FHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaE30rpdRS7DP1XYZee1G69d1UhwmMOy0',
    appId: '1:728113313967:android:19b744640b00b107033c5a',
    messagingSenderId: '728113313967',
    projectId: 'itgustmobileplatform',
    storageBucket: 'itgustmobileplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG62Xml6yV0gr3WE1gwSod0Bc324dJ688',
    appId: '1:728113313967:ios:61015fb547de05a6033c5a',
    messagingSenderId: '728113313967',
    projectId: 'itgustmobileplatform',
    storageBucket: 'itgustmobileplatform.appspot.com',
    iosBundleId: 'com.example.appEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG62Xml6yV0gr3WE1gwSod0Bc324dJ688',
    appId: '1:728113313967:ios:61015fb547de05a6033c5a',
    messagingSenderId: '728113313967',
    projectId: 'itgustmobileplatform',
    storageBucket: 'itgustmobileplatform.appspot.com',
    iosBundleId: 'com.example.appEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuHatwUC-iMkIPE8BjdRPNxqKDuzObAns',
    appId: '1:728113313967:web:e417c71bb68fb12e033c5a',
    messagingSenderId: '728113313967',
    projectId: 'itgustmobileplatform',
    authDomain: 'itgustmobileplatform.firebaseapp.com',
    storageBucket: 'itgustmobileplatform.appspot.com',
    measurementId: 'G-7PR4GV7CB7',
  );
}
